name: Run tests

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    test_pipeline:
        runs-on: ubuntu-20.04
        env:
            TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
            SECRET: TestingSecret381928310
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Install backend dependencies
              run: npm install
            - name: Start backend server
              run: |
                npm run start:test &
                sleep 2
            - name: Run backend unit tests
              run: npm test
            - name: Install frontend dependencies
              run: npm install
              working-directory: ./frontend
            - name: Run frontend unit tests
              run: npm test
              working-directory: ./frontend
            - name: Run end-to-end tests
              uses: cypress-io/github-action@v6 
              with:
                command: npm run test:e2e
                wait-on: http://localhost:3003